### ISSUE TITLE
problem installing on macOS Mojave

### ISSUE THREAD

**Issue by allisp** [martinber/noaa-apt#29] opened 2020-08-23 14:24 UTC
installed gtk+3 ok,
however 

$ cargo build 
   Compiling pin-project-internal v0.4.16
   Compiling futures-macro v0.3.5
   Compiling serde_derive v1.0.110
   Compiling gtk v0.8.1
   Compiling jpeg-decoder v0.1.19
   Compiling image v0.23.4
The following warnings were emitted during compilation:

warning: /opt/local/bin/ranlib: object: /Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/libforeground.a(foreground.o) malformed object (unknown load command 1)
warning: ar: internal ranlib command failed

error: failed to run custom build command for `gtk v0.8.1`

Caused by:
  process didn't exit successfully: `/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-ae98e59d39b0cd5d/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/src/foreground.o" "-c" "src/foreground.m"
exit code: 0
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
running: "ar" "crs" "/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/libforeground.a" "/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/src/foreground.o"
cargo:warning=/opt/local/bin/ranlib: object: /Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/libforeground.a(foreground.o) malformed object (unknown load command 1)
cargo:warning=ar: internal ranlib command failed
exit code: 1

--- stderr

error occurred: Command "ar" "crs" "/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/libforeground.a" "/Users/steve/noaa-apt-1.2.0/target/debug/build/gtk-6026438d05591d21/out/src/foreground.o" with args "ar" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

---------------------
I'm using build because I did a --release before gtk+ was correctly installed

Any help much appreciated

Steve

**Comment by martinber** [comment] 2020-08-23 17:38
Hello,

Sadly I don't really know what the problem is since I never used Mac. Looks like some problem with homebrew and that sort of thing, which makes you have a wrong version of the program called "ar".

Is cctools installed?

    brew install cctools

Do you know about MacPorts? (me not), you could try installing cctools from there.

You could have the program "ar" installed several times, can you search your computer? You can try this command but I'm not sure if it will indicate the locations of all of them

    whereis ar

You can have this program installed generally in these folders:

- `/usr/local/bin`
- `/usr/bin/`
- `/opt/local/bin/`
- `/opt/bin/`

References:

- https://github.com/rust-lang/backtrace-rs/issues/128
- https://github.com/commercialhaskell/stack/issues/4380
- https://stackoverflow.com/questions/52794353/unable-to-compile-actix-on-macos-mojave-due-to-ar-crs-malformed-object-unkno

**Comment by allisp** [comment] 2020-08-23 17:54
I have ar installed OK, I think the issue is a malformed object - see previous trace
I have rustc 1.45.2 installed

**Comment by martinber** [comment] 2020-08-23 19:09
Yes, "ar" is installed but I think it should be using another version of the program. I say this because I see everyone with this issue on the internet has that kind of problem. More references:

- https://github.com/pyenv/pyenv/issues/1267
- https://stackoverflow.com/questions/54363030/cannot-install-any-version-of-ruby-on-mojave-internal-ranlib-command-failed

I wanted to ask, are you used to these kind of things or this is the first time you use brew/MacPorts?

Try running `cargo clean` and `cargo build` again. Also try `brew uninstall cctools` and `cargo build`, and `brew install cctools` and `cargo build`.

**Comment by martinber** [comment] 2020-10-11 11:32
Closing because I think it must be a problem with homebrew, macports, etc. You can comment and re-open if you need more help

**Closed by martinber** 2020-10-11 11:32 UTC
